### ISSUE TITLE
prerender throws TypeError: path must be a string or Buffer

### ISSUE THREAD

**Issue by cubodehelio** [mapbox/docbox#21]
Actually the babel stage works fine but the resulting `lib/render.js` fails.
```
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at Object.<anonymous> (/***/docbox/dist/render.js:46:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

**Comment by cubodehelio** [comment]
nevermind, I think I was using it wrong
